# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cf12c37a984951ff38f4276696f059f9819ad7f2b696085def8e9450d09850eed1918d8e92834688fbc7f99000039564cc480fb36da85c63faaa553d80961fc

test:
  secret_key_base: 702564901d58d55d65367db93944a857fbe57ee544e6e65c14399368b0f72b8551e0b7be7e7457bc1aef1e33426dcbb5e42c4117762a763ff3afcc260efc8f11

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
